import { Router } from 'express';
import { asyncHandler, authorize, protect, validate } from '../middleware/index.js';
import { registerSchema, loginSchema, projectSchema, projectUpdateSchema, memberSchema, taskSchema, taskUpdateSchema } from '../validators/index.js';
import { auth, users, projects, tasks, dashboard, notifications } from '../controllers/index.js';

export const api = Router();
api.get('/health', (_req, res) => res.json({ success: true, status: 'ok' }));
api.post('/auth/register', validate(registerSchema), asyncHandler(auth.register));
api.post('/auth/login', validate(loginSchema), asyncHandler(auth.login));
api.get('/auth/me', protect, asyncHandler(auth.me));
api.get('/users', protect, authorize('ADMIN'), asyncHandler(users.list));
api.get('/users/directory', protect, asyncHandler(users.directory));
api.get('/projects', protect, asyncHandler(projects.list));
api.post('/projects', protect, validate(projectSchema), asyncHandler(projects.create));
api.get('/projects/:id', protect, asyncHandler(projects.get));
api.put('/projects/:id', protect, validate(projectUpdateSchema), asyncHandler(projects.update));
api.delete('/projects/:id', protect, asyncHandler(projects.remove));
api.patch('/projects/:id/archive', protect, asyncHandler(projects.archive));
api.post('/projects/:id/members', protect, validate(memberSchema), asyncHandler(projects.addMember));
api.delete('/projects/:id/members/:userId', protect, asyncHandler(projects.removeMember));
api.get('/tasks', protect, asyncHandler(tasks.list));
api.post('/tasks', protect, validate(taskSchema), asyncHandler(tasks.create));
api.get('/tasks/:id', protect, asyncHandler(tasks.get));
api.put('/tasks/:id', protect, validate(taskUpdateSchema), asyncHandler(tasks.update));
api.delete('/tasks/:id', protect, asyncHandler(tasks.remove));
api.get('/dashboard', protect, asyncHandler(dashboard));
api.get('/notifications', protect, asyncHandler(notifications.list));
api.patch('/notifications/read-all', protect, asyncHandler(notifications.readAll));
api.patch('/notifications/:id/read', protect, asyncHandler(notifications.read));
