import { useEffect } from 'react';
import { useDispatch, useSelector } from 'react-redux';
import { AlertTriangle, CheckCircle2, CircleDot, FolderKanban, ListChecks, ListTodo, Siren, Timer } from 'lucide-react';
import { fetchDashboard } from '../store';
import { Badge, ErrorState, Loading, PageHeader } from '../components/ui';

export default function DashboardPage() {
  const dispatch = useDispatch(); const data = useSelector((s) => s.dashboard); const user = useSelector((s) => s.auth.user);
  useEffect(() => { dispatch(fetchDashboard()); }, [dispatch]);
  if (data.loading && !data.metrics) return <Loading label="Loading dashboard…"/>;
  if (data.error && !data.metrics) return <ErrorState message={data.error} onRetry={() => dispatch(fetchDashboard())}/>;
  const m = data.metrics || {}; const cards = [
    ['Total projects', m.totalProjects, FolderKanban, 'bg-violet-100 text-violet-700'], ['Active projects', m.activeProjects, CircleDot, 'bg-blue-100 text-blue-700'], ['Completed projects', m.completedProjects, CheckCircle2, 'bg-emerald-100 text-emerald-700'], ['Total tasks', m.totalTasks, ListChecks, 'bg-cyan-100 text-cyan-700'], ['Pending tasks', m.pendingTasks, ListTodo, 'bg-amber-100 text-amber-700'], ['Completed tasks', m.completedTasks, CheckCircle2, 'bg-teal-100 text-teal-700'], ['Overdue tasks', m.overdueTasks, Timer, 'bg-rose-100 text-rose-700'], ['High priority', m.highPriorityTasks, Siren, 'bg-orange-100 text-orange-700'],
  ];
  return <div className="dashboard-view"><PageHeader title={`Good to see you, ${user?.name?.split(' ')[0]}`} description="Here is the current state of your accessible work."/><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(([label, value, Icon, color], index) => <div key={label} style={{ '--card-delay': `${index * 45}ms` }} className="dashboard-metric rounded-2xl border border-slate-100 bg-white p-5 shadow-soft dark:border-slate-800 dark:bg-slate-900"><div className={`metric-icon mb-4 grid h-10 w-10 place-items-center rounded-xl ${color}`}><Icon className="h-5 w-5"/></div><p className="text-3xl font-black text-slate-950 dark:text-white">{value ?? 0}</p><p className="mt-1 text-sm text-slate-500">{label}</p></div>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-[1.3fr_.9fr]"><section className="dashboard-panel rounded-2xl border border-slate-100 bg-white p-6 shadow-soft dark:border-slate-800 dark:bg-slate-900"><h2 className="text-lg font-bold">Project progress</h2><div className="mt-5 space-y-5">{data.projectProgress.length ? data.projectProgress.map((p) => <div key={p._id}><div className="mb-2 flex justify-between text-sm"><span className="font-semibold">{p.name}</span><span className="text-slate-500">{p.completed} / {p.total} tasks · {p.percent}%</span></div><div className="h-2.5 overflow-hidden rounded-full bg-slate-100 dark:bg-slate-800"><div className="dashboard-progress h-full rounded-full bg-brand-600" style={{ width: `${p.percent}%` }}/></div></div>) : <p className="py-8 text-center text-sm text-slate-500">No project activity yet.</p>}</div></section><section className="dashboard-panel rounded-2xl border border-slate-100 bg-white p-6 shadow-soft dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-2"><AlertTriangle className="h-5 w-5 text-rose-500"/><h2 className="text-lg font-bold">Overdue tasks</h2></div><div className="mt-4 divide-y divide-slate-100 dark:divide-slate-800">{data.overdueTasks.length ? data.overdueTasks.map((task) => <div key={task._id} className="py-3"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold">{task.title}</p><p className="mt-1 text-xs text-slate-500">{task.project?.name} · due {new Date(task.dueDate).toLocaleDateString()}</p></div><Badge value={task.priority}/></div></div>) : <p className="py-8 text-center text-sm text-slate-500">Nothing is overdue.</p>}</div></section></div></div>;
}
